### ISSUE TITLE
Resubmissions - why?

### ISSUE THREAD

**Issue by HjalteParner** [ices-eg/wg_WGAcousticGov#10] opened 2020-12-04 12:07 UTC
At the data centre we have noticed that especially the biotic data typically gets resubmitted many times – often during post cruise meetings where the acoustic and biotic data are aligned and the abundance indices estimates calculated. Why is this? Could we perhaps implement some further checks that will help to get the process more streamlined?

**Comment by SMLusseau** [comment] 2020-12-10 10:22
There are various reasons for this happening quite a bit in the HERAS post cruise meetings for example. Some of this has to do with some national data only being ready very close to the post cruise meeting and sometimes the data may have been uploaded slightly prematurely for this reason in a rush to get things in and ready for the post cruise meet. National checking procedures may only be finalized in tandem with the postcruise meeting starting and errors discovered will be fixed at the beginning of the meeting.
Other issues we have had that caused resubmissions at least once during the meetings:
**StockID codes:** In StoX aggregation of abundance by stock requires that all cruises in a project use the same stockID code. The ICES database may now be backwards compatible with all previous allowed stock codes, but StoX will still treat them as different stocks. This has created headaches for us at post cruise meets to make sure everybody uploaded with the same stockID code (not all national databases follow the change in stock ID code as quickly as ICES invents them :-( ). Here it could indeed be helpful if we could automatically convert all the validly used codes to the most recent ICES code on exporting to StoX XML (including leaving blanks as blank).
**Age data:** : The old struggle with winter rings versus years. Some national databases holds herring data in years and some in winterrings. Several times we have only discovered at the post cruise meeting that some cruises have been uploaded with age in winterrings and some with age in years. This is entirely caused by the biotic file guidance in my opinion. It states that the age field is in years. For herring stocks covered by HERAS surveys however age has to be delivered in winter rings to be compatible with the assessments the acoustic indices are used in. We have a separate request to be able to specify whether the age is in winter rings or years in the database so I will no go into detail here with this. We carry out checks at the post cruise meeting on the uploaded data to spot discrepancies by comparing age at length between neighbouring cruises in the survey.
**Maturity** In HERAS the survey group has decided to not upload maturity 66 to the database to avoid problems at the estimation stage. Most tend to forget that until we are sitting together at the post cruise meeting. Stage 66 is used for a variety of abnormal gonad development observed and cannot easily be given a mature or immature label in the analysis based on the maturity stage. As they are relatively rare the easiest way to deal with them at this stage is to not upload them and let StoX give them an expected maturity (MAT or IMM) based on other fish of similar length and age in the same or neighbouring hauls. It could be beneficial if we could avoid tampering with the data that goes into the database, but at the moment StoX is not able to filter these stages out at the analysis stage. Preferred option is to upload all data (to avoid cleaning out info that could be useful at a later stage or in a different analysis) and the have the option in StoX to filter the stages of interest and also combined stages into bigger groups directly in StoX. I think they are working on providing this more flexible approach which would also avoid having to fix levels of MAt and IMM in the StoX XML output from the ICES DB.
**Newcomers** The last major issue causing reupload of data during the postcruise is when someone new takes over the delivery of data for a cruise and are not aware of survey specific foibles (like uploading ages in years instead of WR, or using a different stock code compared to the rest of the cruises). I don't think there needs to be a database check on this - but I think the survey group needs to issue guidelines for how the survey group uses the database (what is required in what format for the exported StoX XML to be compatible with the way the group needs to analyse the data in StoX for example.) These survey specific guidelines could well be part of the Survey manual.

**Comment by CiaranOD** [comment] 2020-12-10 17:11
I think Susan has summarised the issue here very well. When combining large data in a post-cruise meeting setting things invariably change and are refined. To a degree, some changes are unavoidable to ensure the quality fo the data product.

**Comment by CiaranOD** [comment] 2021-01-21 10:08
This issue was discussed at WGIPS (Jan, 2021). Within WGIPS, busy periods coincide with post-cruise meetings and the upload of multiple national data sets over a short time period. For HERAS surveys particularly, resubmission traffic is associated with corrections for Ageing data, Maturity data and to a lesser extent new portal users. 
For **age data**: a consistent point of error is the submission of ages in years instead of winter rings (wr) as is internationally agreed. This has been addressed and wr will now be included in the biotic file going forward @HjalteParner 
For **maturity data**: the reporting of has been complicated within the repository by requiring adherence to international maturity scales (6pt) versus national scales (8pt) resulting in a loss of resolution. This will be addressed in part in version >3.0 of StoX.
For **new users**: as part of the ToR(d) of AcousticGov is to facilitate the training of new users that will help to address upload issues.

**Closed as completed by CiaranOD** 2021-01-21 10:08 UTC
Labels: help wanted
